# Generated by Django 5.2.7 on 2025-11-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile_date_of_birth_employeeprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
